/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PrdRouteImport } from './routes/prd'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRepoTicketRouteImport } from './routes/runs_.$repo.$ticket'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdRoute = PrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRepoTicketRoute = RunsRepoTicketRouteImport.update({
  id: '/runs_/$repo/$ticket',
  path: '/runs/$repo/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/prd': typeof PrdRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/runs/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/prd': typeof PrdRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/runs/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/prd': typeof PrdRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/runs_/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/costs'
    | '/instances'
    | '/lessons'
    | '/prd'
    | '/runs'
    | '/settings'
    | '/terminal'
    | '/runs/$repo/$ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/costs'
    | '/instances'
    | '/lessons'
    | '/prd'
    | '/runs'
    | '/settings'
    | '/terminal'
    | '/runs/$repo/$ticket'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/costs'
    | '/instances'
    | '/lessons'
    | '/prd'
    | '/runs'
    | '/settings'
    | '/terminal'
    | '/runs_/$repo/$ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CostsRoute: typeof CostsRoute
  InstancesRoute: typeof InstancesRoute
  LessonsRoute: typeof LessonsRoute
  PrdRoute: typeof PrdRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  TerminalRoute: typeof TerminalRoute
  RunsRepoTicketRoute: typeof RunsRepoTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd': {
      id: '/prd'
      path: '/prd'
      fullPath: '/prd'
      preLoaderRoute: typeof PrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs_/$repo/$ticket': {
      id: '/runs_/$repo/$ticket'
      path: '/runs/$repo/$ticket'
      fullPath: '/runs/$repo/$ticket'
      preLoaderRoute: typeof RunsRepoTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CostsRoute: CostsRoute,
  InstancesRoute: InstancesRoute,
  LessonsRoute: LessonsRoute,
  PrdRoute: PrdRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  TerminalRoute: TerminalRoute,
  RunsRepoTicketRoute: RunsRepoTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
