/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RunOnceRouteImport } from './routes/run-once'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LoopRouteImport } from './routes/loop'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as RunsRepoTicketRouteImport } from './routes/runs_.$repo.$ticket'
import { Route as LiveRepoTicketRouteImport } from './routes/live.$repo.$ticket'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RunOnceRoute = RunOnceRouteImport.update({
  id: '/run-once',
  path: '/run-once',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopRoute = LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRepoTicketRoute = RunsRepoTicketRouteImport.update({
  id: '/runs_/$repo/$ticket',
  path: '/runs/$repo/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRepoTicketRoute = LiveRepoTicketRouteImport.update({
  id: '/live/$repo/$ticket',
  path: '/live/$repo/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/costs': typeof CostsRoute
  '/inbox': typeof InboxRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/loop': typeof LoopRoute
  '/queue': typeof QueueRoute
  '/run-once': typeof RunOnceRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/projects/new': typeof ProjectsNewRoute
  '/live/$repo/$ticket': typeof LiveRepoTicketRoute
  '/runs/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/costs': typeof CostsRoute
  '/inbox': typeof InboxRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/loop': typeof LoopRoute
  '/queue': typeof QueueRoute
  '/run-once': typeof RunOnceRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/projects/new': typeof ProjectsNewRoute
  '/live/$repo/$ticket': typeof LiveRepoTicketRoute
  '/runs/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRoute
  '/costs': typeof CostsRoute
  '/inbox': typeof InboxRoute
  '/instances': typeof InstancesRoute
  '/lessons': typeof LessonsRoute
  '/loop': typeof LoopRoute
  '/queue': typeof QueueRoute
  '/run-once': typeof RunOnceRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/projects/new': typeof ProjectsNewRoute
  '/live/$repo/$ticket': typeof LiveRepoTicketRoute
  '/runs_/$repo/$ticket': typeof RunsRepoTicketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/costs'
    | '/inbox'
    | '/instances'
    | '/lessons'
    | '/loop'
    | '/queue'
    | '/run-once'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/projects/new'
    | '/live/$repo/$ticket'
    | '/runs/$repo/$ticket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/costs'
    | '/inbox'
    | '/instances'
    | '/lessons'
    | '/loop'
    | '/queue'
    | '/run-once'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/projects/new'
    | '/live/$repo/$ticket'
    | '/runs/$repo/$ticket'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/costs'
    | '/inbox'
    | '/instances'
    | '/lessons'
    | '/loop'
    | '/queue'
    | '/run-once'
    | '/runs'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/projects/new'
    | '/live/$repo/$ticket'
    | '/runs_/$repo/$ticket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRoute
  CostsRoute: typeof CostsRoute
  InboxRoute: typeof InboxRoute
  InstancesRoute: typeof InstancesRoute
  LessonsRoute: typeof LessonsRoute
  LoopRoute: typeof LoopRoute
  QueueRoute: typeof QueueRoute
  RunOnceRoute: typeof RunOnceRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  LiveRepoTicketRoute: typeof LiveRepoTicketRoute
  RunsRepoTicketRoute: typeof RunsRepoTicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-once': {
      id: '/run-once'
      path: '/run-once'
      fullPath: '/run-once'
      preLoaderRoute: typeof RunOnceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop': {
      id: '/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof LoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs_/$repo/$ticket': {
      id: '/runs_/$repo/$ticket'
      path: '/runs/$repo/$ticket'
      fullPath: '/runs/$repo/$ticket'
      preLoaderRoute: typeof RunsRepoTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$repo/$ticket': {
      id: '/live/$repo/$ticket'
      path: '/live/$repo/$ticket'
      fullPath: '/live/$repo/$ticket'
      preLoaderRoute: typeof LiveRepoTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRoute,
  CostsRoute: CostsRoute,
  InboxRoute: InboxRoute,
  InstancesRoute: InstancesRoute,
  LessonsRoute: LessonsRoute,
  LoopRoute: LoopRoute,
  QueueRoute: QueueRoute,
  RunOnceRoute: RunOnceRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  LiveRepoTicketRoute: LiveRepoTicketRoute,
  RunsRepoTicketRoute: RunsRepoTicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
